"""
AI/local_llm.py
Template-based SAR generator — works offline without any API key.
Used as fallback when Gemini is unavailable.
"""
from __future__ import annotations
from datetime import datetime, timezone


def generate_sar_template(verdict: dict) -> dict:
    """
    Generate a professional SAR document from verdict data using templates.
    Returns {"sar_text": str, "source": str, "model": str}
    """
    txn_id   = verdict.get("transaction_id", "N/A")
    account  = verdict.get("account_id",     "N/A")
    meta     = verdict.get("metadata",       {})
    amount   = float(meta.get("amount",      0))
    channel  = meta.get("channel",           "N/A")
    location = meta.get("location",          "N/A")
    risk     = float(verdict.get("risk_score",  0))
    risk_lvl = verdict.get("risk_level",        "N/A")
    rules    = verdict.get("triggered_rules",   [])
    reasons  = verdict.get("top_reasons",       [])
    violations = verdict.get("legal_violations", [])
    rec      = verdict.get("recommendation",    "Standard monitoring")
    today    = datetime.now(timezone.utc).strftime("%d %B %Y")

    # Format indicators
    indicators_text = ""
    for i, r in enumerate(reasons[:5], 1):
        indicators_text += f"  {i}. {r.get('reason', r.get('description', 'N/A'))}\n"
    if not indicators_text:
        indicators_text = "  1. Transaction pattern deviates from account baseline\n"

    # Format legal references
    legal_text = ""
    for v in violations:
        legal_text += (
            f"  • {v.get('act','PMLA 2002')} — {v.get('section','N/A')}\n"
            f"    Description: {v.get('description','N/A')}\n"
            f"    Regulatory Reference: {v.get('rbi_circular','N/A')}\n"
            f"    FATF Basis: {v.get('fatf_ref','N/A')}\n\n"
        )
    if not legal_text:
        legal_text = "  • PMLA 2002 — Section 12: Mandatory STR filing for suspicious transactions\n"

    # SAR ID
    sar_id = f"SAR-{datetime.now().strftime('%Y%m%d')}-{txn_id[:8].upper()}"

    sar_text = f"""
╔══════════════════════════════════════════════════════════════════╗
║           SUSPICIOUS ACTIVITY REPORT (SAR)                      ║
║           Generated by ProofSAR AI — Confidential               ║
╚══════════════════════════════════════════════════════════════════╝

SAR Reference No : {sar_id}
Report Date      : {today}
Reporting Entity : ProofSAR AI Compliance System
Filing Obligation: Prevention of Money Laundering Act (PMLA), 2002

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
SECTION 1: SUBJECT INFORMATION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Account ID       : {account}
Transaction ID   : {txn_id}
Transaction Date : {today}
Amount           : INR {amount:,.2f}
Channel Used     : {channel}
Location/Jurisdiction: {location}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
SECTION 2: SUSPICIOUS ACTIVITY DESCRIPTION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
The ProofSAR AI detection engine has identified the above transaction
as potentially suspicious based on a combined ML probability score of
{risk:.2%} (Risk Level: {risk_lvl}).

AML Pattern(s) Detected: {", ".join(rules) if rules else "Anomalous Behaviour"}

The transaction exhibits characteristics inconsistent with the account
holder's established pattern of financial behaviour and raises concerns
under applicable anti-money laundering regulations.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
SECTION 3: ANALYSIS & RISK INDICATORS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
The following AI-detected risk indicators contributed to this assessment:

{indicators_text}
Composite Risk Score : {risk:.4f} / 1.0000
Risk Classification  : {risk_lvl}
Detection Engine     : ProofSAR AI (ML + Rule-Based Fusion)
Model Used           : {verdict.get('metadata', {}).get('model_used', 'XGBoost/RandomForest')}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
SECTION 4: LEGAL BASIS & REGULATORY MAPPING
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
{legal_text}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
SECTION 5: RECOMMENDED ACTION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
{rec}

This report has been auto-generated by the ProofSAR AI system and should
be reviewed by a qualified AML Compliance Officer before submission to
the Financial Intelligence Unit — India (FIU-IND).

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
CERTIFICATION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
This Suspicious Transaction Report has been prepared in accordance with
the Prevention of Money Laundering Act, 2002 and the RBI guidelines on
Anti-Money Laundering / Combating Financing of Terrorism (AML/CFT).

Report generated by : ProofSAR AI Automated Compliance Engine
Report classification: CONFIDENTIAL — FOR REGULATORY USE ONLY
Generated on        : {today}
""".strip()

    return {
        "sar_text":  sar_text,
        "source":    "local_template",
        "model":     "ProofSAR-Template-v1",
        "sar_id":    sar_id
    }
